apiVersion: apps/v1
kind: Deployment
metadata:
  name: shokujinjp-api
  labels:
    app: shokujinjp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sj-api
  template:
    metadata:
      labels:
        app: sj-api
    spec:
      containers:
      - name: shokujinjp-api
        image: ghcr.io/shokujinjp/api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shokujinjp-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: sj-api
