name: docker
on:
  push:
    branches:
      - "**"

env:
  DOCKER_IMAGE_NAME: shokujinjp/api:latest

jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build
        run: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 -t ${DOCKER_IMAGE_NAME} .