name: docker
on:
  push:
    branches:
      - "master"

env:
  DOCKER_IMAGE_NAME: shokujinjp/api:latest

jobs:
  docker-push:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker login
        if: github.event_name != 'pull_request'
        run: |
          echo  ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: docker build
        run: docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 -t ${DOCKER_IMAGE_NAME} --push .
      - name: Post docker login
        run: rm -rf $(pwd)/.docker
        if: always()